### ISSUE TITLE
How to remove /m modifier?

### ISSUE THREAD

**Issue by sudofox** [lucleroy/php-regex#5]
I'm trying to generate a regular expression to be used in MariaDB REGEXP, which seems to want no surrounding `/`. I worked out that I can omit those by passing an empty string to the `getRegex()` but I'm left with a `m` (multiline modifier) at the end of my string, which I don't want. How can I change the modifiers to omit this?

**Comment by lucleroy** [comment]
Sorry for the delay. I don't know if it's still useful, but here is my answer:
This library is designed to generate regular expressions for PHP, not for other tools. I made some choices to simplify its use. One such choice is to always use the multiline modifier. So you cannot remove it. But you can try to convert the Regex to a string because the `Regex` class implements `__toString` which return the regular expression without delimiters or modifiers. But I don't know if the generated regular expression will still be compatible with MariaDB.
